### ISSUE TITLE
Update Datadog source tag documentation 

### ISSUE THREAD

**Issue by mb-shorai** [falcosecurity/falcosidekick#1017]
**What to document**

Current docs state that Datadog events can be filtered by `sources:falco`: https://github.com/falcosecurity/falcosidekick/blob/2.29.0/docs/outputs/datadog.md?plain=1#L37

Unfortunately, it's not the case, because events contain `source:syscall`, `source:k8s_audit` and so on, specifying only _Falco's_ source: https://github.com/falcosecurity/falcosidekick/blob/aaad6b378dbb612e66d55dc821e88caa85e30282/outputs/datadog.go#L34

Perhaps the easiest way would be to update docs, but I think Falco should in fact add `source:falco` and/or specify both `source:falco` and `source:falco-%falco's-source%`, as well as allow setting custom tags (e.g. to specify env).

**Comment by Issif** [comment]
Hi,

I don't have access anymore to a datadog instance to test some changes. When I integrated this output, years ago, the falco payload didn't contain the `source` field, this is why the datadog event was filled with `source:falco`. I forgot to update the docs after. To avoid to break anything for the end users, the best is just to update the docs. Do you want to create the PR by your own?
