### ISSUE TITLE
Add Google Chat support

### ISSUE THREAD

**Issue by KeisukeYamashita** [falcosecurity/falcosidekick#102]
**Motivation**

Google Chat(former Google Hangout Chat) adoption is increasing these days.

**Feature**

Send notification like Slack and Mattermost

**Alternatives**

**Additional context**

May I add this feature? 
I would like to contribute.

**Comment by Issif** [comment]
@KeisukeYamashita Thanks for idea. I like it.

If you feel to contribute, I'll be glad to review your PR 👍
