### ISSUE TITLE
Multiple alerts sent via AlertManager output when AlertManager HA enabled

### ISSUE THREAD

**Issue by NT-florianernst** [falcosecurity/falcosidekick#1025]
**Describe the bug**

This might be the same bug as #834, but given the lack of details there I opted to rather file a new one. So here goes:

Using AlertManager output to Slack worked just fine in our setup until we enabled AlertManager HA: once that was in place, every event was sent multiple times, reproducibly resulting in receiving 48 Slack messages where a single one should have sufficed.

While this at a first glance looks like an AlertManager issue then, I am still filing it here, as there exists a peculiarity with AlertManager HA which might not be taken into account by Falcosidekick. Of course I might be wrong, though, and please feel free to point out if I indeed am.

**How to reproduce it**

We run Falco and Falcosidekick in AWS EKS and deployed via Helm, with Falcosidekick's values containing
```yaml
config:
  alertmanager:
    hostport: "http://kube-prometheus-kube-prome-alertmanager.monitoring-platform-tasp.svc.cluster.local:9093"
```
The AlertManager is provided by [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/), whose [values default to just a single AlertManager](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L750). With these values everything is running as expected, and Falco events just get sent once to Slack by the AlertManager.

However, once we change kube-prometheus-stack's AlertManager values to build a cluster as per
```yaml
alertmanager:
  alertmanagerSpec:
    replicas: 3
    podAntiAffinity: hard
```
all Falco events will be sent to Slack multiple times.

**Expected behaviour**

No matter how the AlertManager is configured I'd expect only a single event to be sent out. Why am I filing this issue here then? See below at "Additional context".

**Screenshots**

Not applicable.

**Environment**

Adding the details from our Falco pods for the sake of completeness, but basically we are running `falcosidekick:2.29.0`.

- Falco version:
```text
Fri Oct 18 12:32:40 2024: Falco version: 0.38.1 (x86_64)
Fri Oct 18 12:32:40 2024: Falco initialized with configuration files:
Fri Oct 18 12:32:40 2024:    /etc/falco/falco.yaml
Fri Oct 18 12:32:40 2024: System info: Linux version 5.10.215-203.850.amzn2.x86_64 (mockbuild@ip-10-0-33-79) (gcc10-gcc (GCC) 10.5.0 20230707 (Red Hat 10.5.0-1), GNU ld version 2.35.2-9.amzn2.0.1) #1 SMP Tue Apr 23 20:32:19 UTC 2024
{"default_driver_version":"7.2.0+driver","driver_api_version":"8.0.0","driver_schema_version":"2.0.0","engine_version":"40","engine_version_semver":"0.40.0","falco_version":"0.38.1","libs_version":"0.17.2","plugin_api_version":"3.6.0"}
```
- System info:
```text
Fri Oct 18 12:33:53 2024: Falco version: 0.38.1 (x86_64)
Fri Oct 18 12:33:53 2024: Falco initialized with configuration files:
Fri Oct 18 12:33:53 2024:    /etc/falco/falco.yaml
Fri Oct 18 12:33:53 2024: System info: Linux version 5.10.215-203.850.amzn2.x86_64 (mockbuild@ip-10-0-33-79) (gcc10-gcc (GCC) 10.5.0 20230707 (Red Hat 10.5.0-1), GNU ld version 2.35.2-9.amzn2.0.1) #1 SMP Tue Apr 23 20:32:19 UTC 2024
Fri Oct 18 12:33:53 2024: Loading rules from file /etc/falco/falco_rules.yaml
Fri Oct 18 12:33:53 2024: Loading rules from file /etc/falco/rules.d/falco_rules.global.yaml
Fri Oct 18 12:33:53 2024: Loading rules from file /etc/falco/rules.d/falco_rules.workload.yaml
Fri Oct 18 12:33:53 2024: Loading rules from file /etc/falco/rules.d/falco_rules.prod.yaml
{
  "machine": "x86_64",
  "nodename": "falco-daemonset-6fm6v",
  "release": "5.10.215-203.850.amzn2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Tue Apr 23 20:32:19 UTC 2024"
}
```
- Cloud provider or hardware configuration:
  AWS EKS, amd64 worker nodes
- OS:
```text
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel:
```text
Linux falco-daemonset-6fm6v 5.10.215-203.850.amzn2.x86_64 #1 SMP Tue Apr 23 20:32:19 UTC 2024 x86_64 GNU/Linux
```
- Installation method:
  [Kubernetes Helm charts](https://github.com/falcosecurity/charts)

**Additional context**

So why am I filing this here:

The AlertManager HA seems to be rather peculiar. The [AlertManager HA documentation](https://github.com/prometheus/alertmanager#high-availability) states:
```text
Important: Do not load balance traffic between Prometheus and its Alertmanagers,
but instead point Prometheus to a list of all Alertmanagers. The Alertmanager
implementation expects all alerts to be sent to all Alertmanagers to ensure high availability.
```

However, such load balancing of traffic is just what we did, which is in line with the [Falcosidekick documentation](https://github.com/falcosecurity/falcosidekick/blob/master/docs/outputs/alertmanager.md#configuration) for `alertmanager.hostport` as [confirmed in #305](https://github.com/falcosecurity/falcosidekick/issues/305#issuecomment-1031350579): these K8s-internal services are just load balancing requests to any one of the relevant pods and not to all of them as AlertManager HA seems to expect.

I understand that Falcosidekick's `alertmanager.hostport` only accepts a ***single endpoint***, whereas it seems that AlertManager expects to receive events on ***multiple endpoints once AlertManager HA is active***. Hence filing this issue here: could Falcosidekick be extended to allow a ***list of endpoints*** for `alertmanager.hostport` and to then send any events to ***all*** of them?

Thanks in advance for any input on this, and of course thanks a lot for providing Falco in the first place.

**Comment by Issif** [comment]
Hi, 

I see your point. I never used this HA feature in AlertManager, I learned something, thanks.

It's doable to change the behavior of the `alertmanager.hostport`, I'll just keep the name (no plural) to avoid the breaking changes.

FYI, I'm off the next week, and then I'll travel for giving talks, I'm expecting to propose a PR after the KubeCon NA only.
