### ISSUE TITLE
Falcosidekick uses incorrect name for cloudevent spec attribute

### ISSUE THREAD

**Issue by sc-justin** [falcosecurity/falcosidekick#1050]
**Describe the bug**
When setting up falcosidekick to transfer falco events to a cloudevents broker such as knative, it throws the following error:

```
[ERROR] : CloudEvents - extension:event_source: bad key, CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z'), upper-case letters ('A' to 'Z') or digits ('0' to '9') from the ASCII character set
```
This is due to [this line](https://github.com/cloudevents/sdk-go/blob/24f83eb0a86d9cd7f4f28759f823fa77f58b0910/v2/event/extensions.go#L53) of the cloudevents go-sdk. More precisely, it is due to the fact that falcosidekick uses [an underscore in an extension attribute name](https://github.com/falcosecurity/falcosidekick/blob/master/outputs/cloudevents.go#L364) when it should not according to the [Extension Context Attributes section of the CloudEvents spec](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#extension-context-attributes).

**How to reproduce it**
Install falco with falcosidekick exporting events to a cloudevents broker such as knative. Follow for instance [this blog post](https://falco.org/blog/falcosidekick-response-engine-part-3-knative/).

**Expected behavior**
Falcosidekick should not use an underscore in the extension attribute name. The attribute name should only use lower-case letters and digits.

### Environment

**Falco version:**
{"default_driver_version":"7.3.0+driver","driver_api_version":"8.0.0","driver_schema_version":"2.0.0","engine_version":"43","engine_version_semver":"0.43.0","falco_version":"0.39.1","libs_version":"0.18.1","plugin_api_version":"3.7.0"}

**Cloud provider or hardware configuration:**
Google Cloud (GKE)

**OS:**
Debian GNU/Linux 12 (bookworm)

**Kernel:**
Linux falco-45mtj 6.1.100+ #&NoBreak;1 SMP PREEMPT_DYNAMIC Sat Aug 24 16:19:44 UTC 2024 x86_64 GNU/Linux

**Installation method:**
Kubernetes

**Comment by Issif** [comment]
Thank you for this very detailed issue. I'll take care of it once back from KubeCon NA

**Comment by bluehawk27** [comment]
@Issif is there a planned release date for Falcosidekick 2.x that gets this fix in?

**Comment by Issif** [comment]
> @Issif is there a planned release date for Falcosidekick 2.x that gets this fix in?

I'm hoping to release the 2.30 in the next weeks.
