### ISSUE TITLE
Datadog output using Datadog Logs

### ISSUE THREAD

**Issue by yohboy** [falcosecurity/falcosidekick#1052]
**Motivation**

Current Datadog output uses the Datadog Event feature.  
We have a different usage in mind, using Datalog Logs to ingest Falco events.  
It would allow a smoother integration with the Cloud SIEM Datadog feature to centralize all alerts (including falco events). 

**Feature**

Add Datadog output using Logs feature.  
A design may be discussed because a Datadog output already exist.

- Should we create a complete new output for Datadog Logs without any modification to the current Datadog event output?  
- Should we create a new parameter `mode: (event | logs)` within the current Datadog output, with a default mode to event (so no breaking change)?
- Something different?

WDYT?

If we agree on a design, I can work on the implementation.

**Alternatives**

An alternative would be to use the S3 output to store Falco event in S3, then a Datadog forwarder within AWS (using lambda etc) to push falco events to Datadog logs. It is not ideal because it adds some intermediaries and increases the pricing for no real reason.

**Additional context**

**Comment by Issif** [comment]
Hi @yohboy,

This is a good idea. To avoid any breaking change, a new output would be better. I don't have access to a Datadog account, feel free to propose an implementation.

Regards,

**Comment by yohboy** [comment]
Hi @Issif thank you for your answer!

I agree a new output would definitely avoid any breaking change, but I presume it would add some confusion if there are 2 datadog outputs.

First one will be named `datadog` and related to datadog events.
The second one will be named `datadog_logs?` and related to datadog logs.

It may be not fully clear for everyone. But renaming the first output would cause some breaking changes.

Regards,

**Comment by yohboy** [comment]
Hi @Issif , 

can you tell me how is working the release cycle of this project? I see that the last release was in July.  
When will the 2.30 version be released? Asking because I would like to integrate the new output in the falcosidekick helm chart.

**Comment by Issif** [comment]
There is no precise schedule, I release a new version when I consider we have enough new features or when a major bug has been fixed. For the 2.30, I've in mind to do the release in the next weeks. I'll take care of the Helm chart directly at that time.

**Comment by yohboy** [comment]
Thank you!
