### ISSUE TITLE
Support GCP Cloud Functions and Cloud Run 

### ISSUE THREAD

**Issue by KeisukeYamashita** [falcosecurity/falcosidekick#120]
**Motivation**

I am a heavy user of GCP and also serverless products(Cloud Functions & Cloud Run).

Many documents use Cloud PubSub + Cloud Functions(Playbook). But we must treat the event messages with care because Cloud PubSub message semantics are **at least once** and there might be duplicated messages.

Therefore, the backend Cloud Functions or the Cloud Run has to handle the duplication and it's not that easy. In many cases, it requires a database to share context between the instances of Cloud Functions or Cloud Run services.

I want the Falcosidekick to HTTP request with OAuth token directly to Cloud Function or Cloud Run to make the backend easier to implement.

**Feature**

Support [Cloud Function](https://cloud.google.com/functions) and [Cloud Run](https://cloud.google.com/run). It will use the service account key for authorization.

I want to add the config like below

```diff
gcp:
  credentials: "" # The base64-encoded JSON key file for the GCP service account
+  functions:
+    webhookurl: "" # The URL of the function
+    # minimumpriority: "debug" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
  pubsub:
    projectid: "" # The GCP Project ID containing the Pub/Sub Topic
    topic: "" # The name of the Pub/Sub topic
    # minimumpriority: "debug" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
+  run:
+    webhookurl: "" # The URL of the Cloud Run service
+    # minimumpriority: "debug" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
```

**Alternatives**

**Additional context**

The webhook client can't be used because the OAuth token expires and can't be hardcoded.

**Comment by Issif** [comment]
👍

**Comment by KeisukeYamashita** [comment]
I found out that if the client is out of GCP, it's hard to issue a OAuth ID Token for Cloud Run and Cloud Function....
It requires self-signed private key, etc and I don't think it will be user friendly.

I will close this Issue for now. Please feel free to reopen 🙇

**Comment by Issif** [comment]
Is that an issue we may face with PubSub too? Does it worth to specify it in read me?

**Comment by KeisukeYamashita** [comment]
> Is that an issue we may face with PubSub too? 

No, this issue is only happens for [Cloud Function](https://cloud.google.com/functions), [Cloud Run](https://cloud.google.com/run) or [Cloud IAP](https://cloud.google.com/iap) protected GCP backends. 
This is because it uses OAuth2.0 or Open ID connect authn which requires complicated workflow to issue an ID token 😢 

> Does it worth to specify it in read me?

I think if there are more request adding this feature, I can go on. I'll see how it goes for a while if there is more usecase for supporting this feature or not.

**Comment by Issif** [comment]
> > Is that an issue we may face with PubSub too?
> 
> No, this issue is only happens for authn enabled [Cloud Function](https://cloud.google.com/functions), [Cloud Run](https://cloud.google.com/run) or [Cloud IAP](https://cloud.google.com/iap) protected GCP backends.
> This is because it uses OAuth2.0 or Open ID connect authn which requires complicated workflow to issue an ID token 😢

Ok, thanks for the details.

> 
> > Does it worth to specify it in read me?
> 
> I think if there are more request adding this feature, I can go on. I'll see how it goes for a while if there is more usecase for supporting this feature or not.

If someone asks for, we'll refer to this issue.
