### ISSUE TITLE
Migrate Slack attachments to block kit

### ISSUE THREAD

**Issue by KeisukeYamashita** [falcosecurity/falcosidekick#134]
**Motivation**

Slack Attachments are now legacy way to post rich messages to Slack. The next generation is [Block Kits](https://api.slack.com/block-kit).
Not only it is legacy, Attachments has limit that the emojis are displayed as "emojis" like below and kinda ugly now(See `:true:` emoji): 

![image](https://user-images.githubusercontent.com/23056537/101158841-c5a31080-366f-11eb-81bb-ee4e87919fa7.png)

We can disable this and show as plain text if we use the latest generation Block kit.

**Feature**

Use Slack Block Kit as posting rich messages.

**Alternatives**

**Additional context**

If it looks fine to the maintainers, I would be happy to work on this 🚀

**Comment by Issif** [comment]
@KeisukeYamashita I don't know why we may disagree ^^

Slack was the first of all ouputs, I created `falcosidekick`, because I disliked the format with the example given in documention.

I'll help you with that output if you want, we must not loose a feature or break something, it's used a lot.

**Comment by KeisukeYamashita** [comment]
I found that the messages with block kit is not rich...

[This](https://app.slack.com/block-kit-builder/T0256J926#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22text%22:%22A%20message%20*with%20some%20bold%20text*%20and%20_some%20italicized%20text_.%22,%22type%22:%22mrkdwn%22%7D,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*fd.name*%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*proc.cmdline*%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%22/bin/hack%22%7D,%7B%22type%22:%22plain_text%22,%22text%22:%22aKey%22%7D%5D%7D%5D%7D) is kinda example of the message that I created on Block kit builder.(I only added few block ) 

Do you think it's worth migrating it?

**Comment by Issif** [comment]
@KeisukeYamashita I don't have access to your Slack, please share a screenshot.

If we lose features with block kit, I don't think it's a good idea to migrate. I like the style of current notifications in Slack

**Comment by KeisukeYamashita** [comment]
Sorry for that.

![image](https://user-images.githubusercontent.com/23056537/101643475-86156380-3a77-11eb-94db-7f9b944952fe.png)

Block kit can create only simple messages with no color or attachments....
I think it's not worth migrating to block kit. I will close this 🙇

**Comment by Issif** [comment]
I agree. Thanks your idea and your tests.
