### ISSUE TITLE
Suppor PagerDuty as output

### ISSUE THREAD

**Issue by KeisukeYamashita** [falcosecurity/falcosidekick#163]
**Motivation**

In my company, we use PagerDuty as a pager system.
If there are high-level priority detection, I want to get a call.

**Feature**

Page Pagerduty team if the output of Falco is higher than the minimunpriority.

**Alternatives**

**Additional context**

**Comment by Issif** [comment]
I know the tool and their API but I don't use it anymore (OpsGenie now), I can review if you submit something.

Thanks

**Comment by KeisukeYamashita** [comment]
Okay, I will raise a PR.
I wanted to confirm to you before doing something. Thanks!🙏

**Comment by Issif** [comment]
I'll never refuse a new output, as long it makes sense for people. 😉
