### ISSUE TITLE
Alertmanager forwarder only add fields for string values.

### ISSUE THREAD

**Issue by alsm** [falcosecurity/falcosidekick#176]
**Motivation**

I'm using falco to capture events where some of the fields values are numbers (network ports) and would like that information in the alertmanager alert fields

**Feature**

Currently anything not a string is ignored, for at least integer values it should be simple enough to convert to a string and add to the alert labels.

Assuming this is accepted I'm happy to make a PR for it.

**Comment by Issif** [comment]
Hi @alsm 

I'm totally OK with that, please propose a PR or I'll do it myself if you can't.
