### ISSUE TITLE
Unable to add more than one custom field with Helm

### ISSUE THREAD

**Issue by Rajakavitha1** [falcosecurity/falcosidekick#188]
**Describe the bug**

**How to reproduce it**

Install Falcosidekick with Helm and add more than one custom fields.
<img width="1110" alt="Screenshot 2021-02-01 at 8 11 37 PM" src="https://user-images.githubusercontent.com/37059749/107462991-4ce69600-6b83-11eb-98d4-ef219518b8e4.png">

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Issif** [comment]
Thanks @Rajakavitha1 

This issue comes from helm templating, to solve it, you have to escape the comma: `--set falcosdeikick.config.customfields="environment:production\,datacenter:mumbai"`

I already added in my WIP PR for next helm chart release.

👍
