### ISSUE TITLE
Refactor PagerDuty output to use Events v2 API

### ISSUE THREAD

**Issue by caWhite** [falcosecurity/falcosidekick#197]
**Motivation**

PagerDuty's [API documentation](https://developer.pagerduty.com/docs/rest-api-v2/rest-api/) states that the Events v2 API should be used by monitoring tools instead of the Rest API.

`
The REST API provides a way for third parties to connect to a PagerDuty account and access or manipulate configuration data on that account. It is not for connecting your monitoring tools to send events to PagerDuty; for that, use the Events API.
`

**Feature**

Replace the existing `PagerdutyCreateIncident` call with one that sends a POST request to the https://events.pagerduty.com/v2/enqueue endpoint. This would remove the `APIKey`, `Asignee`, `EscalationPolicy`, and `Service` configuration options, and consolidate alert routing/authentication via a provided routing key (see API syntax [here](https://developer.pagerduty.com/docs/events-api-v2/trigger-events/))

**Alternatives**

**Additional context**

I've spiked out an [initial changeset](https://github.com/caWhite/falcosidekick/blob/feat/pagerduty/outputs/pagerduty.go).  If the proposed change makes sense, I'd be happy to submit a PR.

**Comment by KeisukeYamashita** [comment]
> PagerDuty's API documentation states that the Events v2 API should be used by monitoring tools instead of the Rest API

I didn't know that.

> If the proposed change makes sense, I'd be happy to submit a PR.

It makes sense, could you submit a PR 🙏  I can review. Thanks in advance.
