### ISSUE TITLE
Slack Output w/ SLACK_OUTPUTFORMAT of "fields" same as "all"

### ISSUE THREAD

**Issue by mike-stewart** [falcosecurity/falcosidekick#203]
**Describe the bug**

It appears that the behaviour of setting SLACK_OUTPUTFORMAT = 'fields' is the same as SLACK_OUTPUTFORMAT = 'all'.

The [README indicates](https://github.com/falcosecurity/falcosidekick#slack) that setting `SLACK_OUTPUTFORMAT = 'fields'` should result in only fields being added to the Slack attachment, with no text blob. This does not work.

I think this was a regression introduced here: https://github.com/falcosecurity/falcosidekick/pull/62/files#diff-f7900a5d2fd433bc5d3a2f71cf9f90966e891d82cd5642cba6a92a5e51280ab6R81

**How to reproduce it**

Set  slack.outputformat: "fields" 

**Expected behaviour**

I expect that setting SLACK_OUTPUTFORMAT = 'fields' should prevent the full text output from being added to slack.

**Screenshots**

With `slack.outputformat: all` and `slack.messageformat: ""`:
<img width="616" alt="before" src="https://user-images.githubusercontent.com/2521245/110216692-ee14f380-7e86-11eb-8ee5-50fe4b801b26.png">

With `slack.outputformat: fields` and `slack.messageformat: "{{ .Priority }}: *{{ .Rule }}*"`:
<img width="615" alt="after" src="https://user-images.githubusercontent.com/2521245/110216700-f705c500-7e86-11eb-9a8d-39f543472a60.png">

**Environment**

- Falco version: 0.27

**Additional context**

**Comment by cpanato** [comment]
thanks @mike-stewart for the report, I will try to reproduce and fix it.
