### ISSUE TITLE
SLACK_OUTPUTFORMAT=fields has no effect

### ISSUE THREAD

**Issue by juris** [falcosecurity/falcosidekick#211]
Falcosidekick 2.21.0 -- changing outputformat from default value (all) to "fields" does not change anything. Slack alerts still have text section.

**Comment by mike-stewart** [comment]
Dupe of #203?

**Comment by mike-stewart** [comment]
@cpanato @Issif Is there an upcoming release planned that will include the fix for this from master?

**Comment by fjogeleit** [comment]
We are planning the next release this week.

**Comment by Issif** [comment]
#203 fixes this issue

**Comment by Issif** [comment]
We released 2.22.0 yesterday with the fix
