### ISSUE TITLE
Prometheus metric labels

### ISSUE THREAD

**Issue by Annegies** [falcosecurity/falcosidekick#214]
We are using Falco-exporter for prometheus metrics and Falco sidekick for it's AWS integration. But since Falco sidekick also exposes the falco_events metric we could use that and stop running Falco-exporter. But the metric from Falco sidekick is missing some essential labels like `k8s_pod_name` and `k8s_ns_name`.

Is it possible to add the same labels as in Falco-exporter?

**Comment by Issif** [comment]
Hello,

There was an issue with these labels, we fixed it and it will be available in upcoming release: https://github.com/falcosecurity/falcosidekick/blob/94fb46953627111e18b06b01d892d91d96807dd1/stats_prometheus.go#L45

**Comment by Annegies** [comment]
Neat! I actually forgot to update the issue. The labels on audit events are different from other events, they don't have the k8s.pod.name and k8s.ns.name fields so the metrics end up without any specification to which pod/resource.

And i was comparing metrics from audit events with the metrics from falco-exporter.
Also in falco-exporter the metrics for audit events lack labels

**Comment by Issif** [comment]
These labels are not present in event from `falco`, for some rules we have `ka.target.namespace`, we might consider to add them.

**Comment by Issif** [comment]
audit logs have a different format, and labels which appear in falco events depends of fields used in the output of the rule.

**Comment by Issif** [comment]
@Annegies I forgot to mention it in 2.22.0 release, but it should be fixed now. Rules which use `k8s.ns.name` and `k8s.pod.name` in their outputs, will have these labels in Prometheus metrics.

See https://github.com/falcosecurity/falcosidekick/blob/94fb46953627111e18b06b01d892d91d96807dd1/handlers.go#L109

Tell me if everything works as expected for you. 🙏
