### ISSUE TITLE
Support AWS Kinesis as an output

### ISSUE THREAD

**Issue by mercion** [falcosecurity/falcosidekick#221]
**Motivation**

We use AWS kinesis to agregate data and it would be great if the falcosidekick could also natively put to Kinesis. 

**Feature**

Add Kinesis as an AWS output option

**Alternatives**

Today we are writing lambdas to take stuff off SQS and push to kinesis, natively pushing to kinesis would make this a lot simpler and portable.

**Comment by mercion** [comment]
Happy to do the work for this, if folks think this is a good idea.

**Comment by Issif** [comment]
As we already support various AWS Services, it should be easy to integrate a new one, feel free to propose a PR. Thanks.

**Comment by gauravgahlot** [comment]
@Issif may I take this up?

**Comment by Issif** [comment]
> @Issif may I take this up?

of course, thank you 🙏
