### ISSUE TITLE
Support Webex Teams as an output

### ISSUE THREAD

**Issue by mercion** [falcosecurity/falcosidekick#222]
**Motivation**

We seem to have a bunch of output plugins for slack, Microsoft teams etc but were missing Webex Teams as an output plugin. 

**Feature**

New output plugin that pushes to webex teams in a similar manner to Microsoft teams. 
https://www.webex.com/team-collaboration.html

**Alternatives**

Could use the HTTP webhook outputs but that really limits rich messages and requires a proxy in the middle.

**Comment by mercion** [comment]
happy to do the work for this one as long as folks think that this is a good idea

**Comment by Issif** [comment]
Hello @mercion I support every new output, feel free to propose a PR, we'll review it for sure. Thanks.
