### ISSUE TITLE
Slack output: Ordered fields

### ISSUE THREAD

**Issue by jonny-wg2** [falcosecurity/falcosidekick#223]
**Motivation**

As reviewing falco events in slack using falcosidekick, I find it difficult to quickly analyze and compare the results from one event to the next. The reason being, I noticed that some fields are consistent in location while others always move and my mind was playing trickery. 

In the example below, you can see that the `time` field is consistently on the bottom (which is great because it's a big field and should be on the bottom) but for example, if I was not printing the `rule` field in the header of the slack message, trying to find the `rule` would be challenging as it moves around in place.

Example of two alerts
![image](https://user-images.githubusercontent.com/39831372/114130984-fb982000-9901-11eb-871f-a812fff0496b.png)

**Feature**

The feature request would be something along the lines of a more structured output. When creating a structured output it can be challenging as some alerts will have metadata that does not exist in other alerts. Additionally, some fields will produce output that takes up a full line vs half line in one event and then a half line vs full line in the second event.

With this said, I believe we could prioritize certain fields and always place them in place x if exists. For example, it appears this is being done with the `time field`.

I could foresee the `rule` field always being the first. Following the fields about the `container` and then `proc` or `cmd` and then others - ending with the `time`

Essentially following the format with answering the questions:

```
- why is this alert firing (rule x)
- on what resource (container y)
- what's the impact (what actions are being performed - proc.cmd)
- when (time)
```

**Comment by Issif** [comment]
Hello I get your point, I'll try some `sort` but I don't know if we have to "highlight" some fields.

**Comment by Issif** [comment]
I was able to get that order, it's kept for all messages. wdyt?

![image](https://user-images.githubusercontent.com/4520100/114311070-8ab55b80-9aed-11eb-89d6-2c1240de70e5.png)

**Comment by jonny-wg2** [comment]
@Issif This is super awesome! 

I could also see this being helpful for teams, discord etc output where a column output is provided.

**Comment by Issif** [comment]
@jonny-wg2 yes, I'll replicate that for all "instant messages" outputs

**Comment by Issif** [comment]
I'm closing this issue, the PR has been merged and the fix will be in next release.

**Comment by jonny-wg2** [comment]
Woot woot thanks @Issif can't wait to test it out
