### ISSUE TITLE
Route events to multiple slack channels

### ISSUE THREAD

**Issue by jonny-wg2** [falcosecurity/falcosidekick#224]
**Motivation**

Background:

One of the most common rules we have alerts on is `Terminal shell in container`. We really like this rule as it is an audit log of when a user accesses a k8s container.

While this rule is not  "security alert" which requires action, it is more of an "audit alert". E.g. `Terminal shell in container` is not the same severity as say `Delete Bash History` or `Unexpected outbound connection destination`

And at the moment all audit logs and severity event logs are going to a dedicated `falco` channel on our slack as it can be  lot of noise. In theory, I would like to be able to route specific events to go just to `events-security` slack channel instead or `infra-audit` channel.

**Feature**

- Have the ability to route events to multiple slack channels based on (either) rule name or severity of alert

**Comment by Issif** [comment]
Hello,

This is a request we already had. I understand the need but it means a lot of changes.

[Here my answer last time](https://github.com/falcosecurity/falcosidekick/issues/161#issuecomment-747714289)

A solution could be to use one the available FaaS Outputs (`Kubeless`, `OpenFaas`, `Knative (Cloud Events)`, `AWS Lambda`) and code yourself the logic.
