### ISSUE TITLE
Integration with the Azure Event Hub

### ISSUE THREAD

**Issue by serxansherif** [falcosecurity/falcosidekick#230]
I want to send logs to the Azure Event Hub. I executed the following command when I installed Falco, I get the below error in the container.

**Command**
_helm install falco falcosecurity/falco
--set falcosidekick.enabled=true
--set falcosidekick.webui.enabled=true
--set falcosidekick.config.azure.subscriptionID="lkjkljj-kjkj-llklk-8c4601adba21"
--set falcosidekick.config.azure.resourceGroupName="ResourceGroupName"
--set falcosidekick.config.azure.podIdentityClientID="af000a07-rfvs-7852-a012-98521edb9b78"
--set falcosidekick.config.azure.podIdentityName="application-identity"
--set falcosidekick.config.azure.eventhub.namespace="abcdy.servicebus.windows.net"
--set falcosidekick.config.azure.eventHub.name="test"
-n falco_

**Error**
_2021/04/14 13:31:38 [ERROR] : AzureEventHub EventHub - neither Azure Active Directory nor SAS token provider could be built - AAD error: failed to refersh token: &{{{ 0 0 0 } 0x2d06db0 {{ false } { false } {http 169.254.169.254 /metadata/identity/oauth2/token false api-version=2018-02-01&resource=https%3A%2F%2Feventhubs.azure.net%2F } { false }} https://eventhubs.azure.net/ true 300000000000} 0xc0005f5f08 0xc0001aed80 [] 5}, SAS error: unable to build SAS token provider because (EVENTHUB_KEY_NAME and EVENTHUB_KEY_VALUE) were empty, and EVENTHUB_CONNECTION_STRING was empty_

Could you please share the configuration guide for Event Hub integration?

**Comment by Issif** [comment]
Hello,

I didn't developed this output myself and don't know Azure, I asked to the person who integrated it to help us with.

**Comment by arminc** [comment]
It's been a while but we ran using AzureIdentity and AzureIdentityBinding, the code basically assumes the credentials will be set by AKS. Behind this line of code there are couple of methods it tries to get the credentials: https://github.com/falcosecurity/falcosidekick/blob/1963830d4e3e21799a2e49e071eb8ff4acedb093/outputs/azure.go#L32

**Comment by NissesSenap** [comment]
If you want to use azure eventhub with the current solution you will need to define 4 environment variables.

```
export AZURE_CLIENT_ID="af000a07-rfvs-7852-a012-98521edb9b78""
export AZURE_CLIENT_SECRET="super-secret-password"
export AZURE_TENANT_ID="000000-0000-0000-0000-0000000"
export AZURE_SUBSCRIPTION_ID="000000-0000-0000-0000-0000"
```
This you can do with with the current helm chart using

`config.extraEnv`

But the bad thing with that is that you have to send in your AZURE_CLIENT_SECRET when installing falco exporter and that isn't awsome from a security point of view. Especieally if you are using GitOps and don't want secrets in your git repo (which you shoulden't).

So the solution for this is to use aadpodidentity (at least if you are running in azure) which is already supported in the helm.
I have written some code that I think will work for this. I will do some verification and I hope that I will be able to provide a PR to improve how we use aadpodidentity in falcosidekick.
