### ISSUE TITLE
[FEATURE] Add Google Cloud Cloud Functions as an output type

### ISSUE THREAD

**Issue by developer-guy** [falcosecurity/falcosidekick#240]
**Motivation**

Cloud Functions is a scalable pay-as-you-go function as a service (FaaS) to run your code with zero server management. In Falcosidekick, there is support available for some Google Cloud services like Storage, Pub/Sub, etc. So, it would be nice to have if we add another Google Cloud service named Cloud Function as an output for the Falcosidekick.

**Feature**

As I mentioned above, we have support for some Google Cloud services in Falcosidekick, we can add the code for Cloud Functions support to the available code used for implementing other Google Cloud services.

**Alternatives**

Alternatively, there is no support for [Cloud Run](https://cloud.google.com/run) which is another FaaS solution in Google Cloud in Falcosidekick, maybe we can add that later.

**Additional context**

**Comment by developer-guy** [comment]
cc: @cartyc @Issif

**Comment by cartyc** [comment]
+ 1 for cloud run.
