### ISSUE TITLE
Support AWS IAM role association with falcosidekick service account

### ISSUE THREAD

**Issue by Kaizhe** [falcosecurity/falcosidekick#257]
**Motivation**

For falcosidekick sending Falco alerts to AWS (e.g. s3 bucket), originally we use `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, however, it will be easier to manage AWS access through IAM role:

https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

**Feature**

In `values.yaml` file:
Add fields `aws.account` and `aws.iamrole`.

In `templates/rbac.yaml`

Add annotation to serviceaccount:
```
 annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.config.aws.accountid }}:role/{{ .Values.config.aws.iamrole }}
```

**Alternatives**

N/A

**Additional context**

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by Kaizhe** [comment]
wrong place

**Comment by Issif** [comment]
no problem 😉 

Anyway, you can take a look at #220, @jonahjon is adding authentication with IRSA
