### ISSUE TITLE
Support Yandex.Cloud outputs

### ISSUE THREAD

**Issue by nar3k** [falcosecurity/falcosidekick#258]
**Motivation**

Yandex.Cloud users also want to use Falco. 

**Feature**

[Yandex Cloud](https://cloud.yandex.com) has multiple services that can be output.  Most demanded output right now is [Yandex.Storage](https://cloud.yandex.com/en-ru/services/storage) which has S3 API and second one is to use Yandex.Cloud Logging ( which is in preview state) 

**Alternatives**

One of the alternatives to modify AWS output to make it support Yandex.Cloud but I think its not correct as Yandex.Cloud has compatability later with AWS S3 API  but not fully compatible

**Additional context**

I could try working on feature by my own

**Comment by Issif** [comment]
Hello,

This is good idea, thank you. I don't know Yandex, but if there S3 service reproduces AWS service, you can take our integration as reference and just override the endpoint in config.
And you're right, it has to be a new separated output.

```yaml
yandex:
	s3:
	   ...
	logs:
       ...
```

👍

**Comment by nar3k** [comment]
Created PR for S3 , Cloud logging will be added later
