### ISSUE TITLE
Feature request: Support for heartbeat messages for outputs

### ISSUE THREAD

**Issue by jceresini** [falcosecurity/falcosidekick#278]
**Motivation**

We would like to send falco messages from multiple clusters to a SIEM. It would be nice if the SIEM could detect if we stopped receiving logs from a given cluster though (for example, if the cluster has an outbound firewall configured that breaks connectivity). We could configure the SIEM to alert if data isn't seen from a given cluster for a certain period of time, if we could guarantee sidekick would send at least some messages on a reasonable interval.

It would be nice to be able to configure a set interval, maybe per-output, to send generic heartbeat-like messages.

**Feature**

Certain outputs could have a config option (or maybe theres a global config option for all outputs) to set the heartbeat interval.
Defaults to no heartbeats.
If configured, sends a message at the provided interval. (for example every hour, or once a day, not overly chatty)

**Alternatives**

Another option could be to allow us to configure liveness probes in the sidekick helm chart that trigger the messages via the `/test` handler in falcosidekick.

**Comment by Issif** [comment]
Hello, 

I don't like the idea to change the liveness probe, this is not its purpose but we can think about something else like you ask.

Heartbeats are a particular use case, I don't think we want to have it for all outputs. A dedicated output should be enough, I guess.

I'll add this in my todo for 2.25.0 and submit a proposal to community.
