### ISSUE TITLE
Require image for ARM64 architecture.

### ISSUE THREAD

**Issue by odidev** [falcosecurity/falcosidekick#285]
Hi Team,

I am trying to use the falcosidekick image on arm64 platform but it seems it is not available for arm64.

I have successfully built the image for arm64 platform, using the command ` docker build -t image_name .`

I have made changes in config.yml file and Makefile and used Circle-CI to push images to docker hub.

**Commit Link** - https://github.com/odidev/falcosidekick/commit/9b3b8d22a2386239d64e8a1d88102bb31f964357

**Docker Hub Link**  - https://hub.docker.com/r/odidev/falcosidekick/tags

Do you have any plans on releasing arm64 images?

If interested, I will raise a PR.

**Comment by Issif** [comment]
Hi,

You're the first one asking for an image for arm64, this is totally something we could have for next release. Please, share with us your PR. I checked your version, can you try to keep the build step inside the Makefile as much as possible.

**Comment by cpanato** [comment]
@Issif I can work on that and make some tests
