### ISSUE TITLE
Falcosidekick caching

### ISSUE THREAD

**Issue by YuranFlow** [falcosecurity/falcosidekick#297]
**Motivation**

So I couldn't find anything about falcosidekick caching received data in the documentation.

I'd like to know if falcosidekick uses caching when one of the outputs isn't able to receive the logs (e.g. elasticsearch) and if not is anything related to caching on the roadmap for the future?

**Comment by Issif** [comment]
Hello,

No caching for now, if one output is unavailable, an error message is printed and that's all. For now, nobody asked for that feature, and we may think about. What's your use case that implies to have it?

**Comment by YuranFlow** [comment]
Does that mean, that the logs the falco instances have generated will be dropped if the output isn't available?

**Comment by YuranFlow** [comment]
I work with a Security Information and Event Management solution and I'm currently testing my grounds with Falco. So it'd be nice that if for any reason elasticsearch is unreachable, the log data will still be received once it is up and running again.

**Comment by Issif** [comment]
> Does that mean, that the logs the falco instances have generated will be dropped if the output isn't available?

Exactly.

I get your point, that something we may think about for future.
