### ISSUE TITLE
Sign release artifacts using cosign

### ISSUE THREAD

**Issue by cpanato** [falcosecurity/falcosidekick#300]
**Motivation**

The idea is to sign the release artifacts using [cosign](https://github.com/sigstore/cosign) when doing the release.

This is an initial step for a more secure release and lets the consumers have the ability to verify the release artifacts.

**Feature**

Our project already uses GoReleaser and that makes it easier to implement the signing part.

We need to decide where we will run the release:

- [ ] If we use GitHub Actions we have a feature that we can sign using a keyless approach

- [ ] If we use the correct way using circleci we will need to generate a private/pub certificate and store the password in a circleci context.

**Alternatives**

n/a

**Additional context**

n/a

**Comment by cpanato** [comment]
cc @Issif @leogr 
/assign @cpanato

**Comment by Issif** [comment]
I like the idea :+1: 

I think we should use CircleCI too, for avoiding to mix the CI solutions and create complexity.

**Comment by cpanato** [comment]
ok cool, i will work for circleci and ping @leogr to synchronize the secrets

**Comment by leogr** [comment]
Hey @cpanato 

I confirm I created the context on CircleCI and set the secrets. :)

**Comment by cpanato** [comment]
thanks @leogr i will finish and push the PR
