### ISSUE TITLE
Error event disappers in the falco dashboard

### ISSUE THREAD

**Issue by saivenkateshedem** [falcosecurity/falcosidekick#303]
**Error priority event is disapering after new event is added**

Whenever a new event is added in the dasboard error event is disappering

**How to reproduce it**
1) Enter into the container using kubectl exec command -> we will get alert in UI
2) Enter any apt command -> we will get error alert in falco UI
3)Close the shell and again execute the kubectl exec command -> now previous error alert is vanishing off

**Expected behaviour**
Error alert should also display in the UI..Whatever alerts will display in UI should persist .so that we can see it in the timeline

**Screenshots**

<img width="1318" alt="Screenshot 2022-01-31 at 4 09 21 PM" src="https://user-images.githubusercontent.com/87964472/151780328-523da3be-376a-49e2-99de-309fd3d921fa.png">

<img width="1303" alt="Screenshot 2022-01-31 at 4 10 20 PM" src="https://user-images.githubusercontent.com/87964472/151780405-d8a90c80-6857-4d58-83ec-1162b1673aeb.png">

**Environment**

- Falco version:
0.30.0
- System info:
Mon Jan 31 10:49:28 2022: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Mon Jan 31 10:49:28 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Jan 31 10:49:28 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Jan 31 10:49:28 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
{
  "machine": "x86_64",
  "nodename": "falco-tn8mr",
  "release": "5.4.117-58.216.amzn2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Tue May 11 20:50:07 UTC 2021"
}
- Cloud provider or hardware configuration: AWS eks
- OS:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel:
Linux falco-tn8mr 5.4.117-58.216.amzn2.x86_64 #1 SMP Tue May 11 20:50:07 UTC 2021 x86_64 GNU/Linux
- Installation method:
kubernetes..using helm charts

**Comment by Issif** [comment]
Hello,

this issue is more related to [falcosidekick-ui](https://github.com/falcosecurity/falcosidekick-ui). I worked one v2 with a totally different storage system (I'm using redis with redissearch module), it should improve a the UX by providing a real API with unlimited storage. For now, UI is not my top priority but we'll work on with @fjogeleit asap.

**Comment by saivenkateshedem** [comment]
Hi @Issif 
okay thanks...
one help..in dashboard it is showing only 200 events...how to show all events..is there any database we use for this.If yes can i know the steps...iam using helm charts for the falco and falcosidekick installation

**Comment by Issif** [comment]
the current version keeps all events in memory, and the UI get them all at once, this is why we limited to last 200, for avoiding to explode the browser memory usage. The new version with redis is not ready at all, the backend seems OK but we need to rewrite the frontend totally. Until that, you can increase the number of events to keep by increasing the retention setting https://github.com/falcosecurity/charts/blob/a7685b58ca2ae15e1256e3cb26eca10156ae147e/falcosidekick/values.yaml#L376
