### ISSUE TITLE
PolicyReport output not working

### ISSUE THREAD

**Issue by r0binak** [falcosecurity/falcosidekick#304]
I set key --set policyreport.enabled=true and its now working

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Issif** [comment]
Hi,

I suppose you're installing Falcosidekick with Helm, but as long the release with this feature (2.25.0) will not be changed for managing this output.

**Comment by r0binak** [comment]
ok. I wait this

**Comment by Issif** [comment]
I'm closing this issue. If you need more, please open a new one in https://github.com/falcosecurity/charts
