### ISSUE TITLE
Add Clustername module Syslog

### ISSUE THREAD

**Issue by fjzito** [falcosecurity/falcosidekick#319]
**Motivation**

Hello everyone im working mercadolibre and create feature for module Syslog.
The change I made was to add the clustername. It is very necessary to know from which cluster the information is received.

How do I propose it in the community?

Thanks.

**Feature**

Add Clustername for module Syslog with this we can recognize from which cluster it comes.

`"output_fields":{"clustername":"test"}`

[https://github.com/falcosecurity/falcosidekick/pull/321](url)

**Comment by Issif** [comment]
Can we close this issue please?
