### ISSUE TITLE
Use of a configmap for k8s deployment

### ISSUE THREAD

**Issue by Issif** [falcosecurity/falcosidekick#33]

**Comment by kamirendawkins** [comment]
Is the goal of this to not only use a `ConfigMap` for non-secret configurations but also to hot-reload when ever said `ConfigMap` changes?

**Comment by Issif** [comment]
That's a good idea. For now, `ConfigMap` is not my top prio, but feel free to create an issue linked to this one for asking hot reloading.

**Comment by sandeeplamb** [comment]
@Issif 1 Question.
What is best practice to install sidekick?
As a sidecar container in Falco Pod or as a separate Chart Altogether?

**Comment by Issif** [comment]
> @Issif 1 Question.
> What is best practice to install sidekick?
> As a sidecar container in Falco Pod or as a separate Chart Altogether?

That's a good question. For now, the only method for deployment is a separated helm chart. I hope to add falcosidekick as a sidecar in official falco helm chart. It will be useful for different reasons :

- only one helm chart to rule them all
- I'm planning to add unix pipe as input
- for pipe, http, gRPC inputs, a single pod makes communications easier (for example, falcosidekick is already able to replace some custom code in that architecture https://sysdig.com/blog/active-kubernetes-security-falco-nats-kubeless/, no more need custom application for pushing events to NATS)
- since falco introduced a gRPC server, we're dealing about how handling multiple falco instances, if we use pods with both falco + falcosidekick, that issue disappears (see : https://github.com/falcosecurity/falco/issues/824)

Hope this answers your interogation.

**Comment by Issif** [comment]
I close this issue, as helm chart is not anymore in this repo. I someone needs this feature, please create a new issue in : https://github.com/falcosecurity/charts
