### ISSUE TITLE
Need a new Dockerhub repo since falcosidekick has migrated ton falcosecurity organization

### ISSUE THREAD

**Issue by Issif** [falcosecurity/falcosidekick#34]
Falcosidekick is now a part of falcosecurity organization, so we need to migrate docker images too. Currently it's on my own account : https://hub.docker.com/r/issif/falcosidekick/.

**Comment by fntlnz** [comment]
Here you go! https://cloud.docker.com/u/falcosecurity/repository/docker/falcosecurity/falcosidekick

**Comment by Issif** [comment]
We need to link the github account to allow auto build.

**Comment by Issif** [comment]
https://hub.docker.com/r/falcosecurity/falcosidekick/tags 😉

**Comment by fntlnz** [comment]
Which GitHub account @Issif ?

**Comment by Issif** [comment]
> Which GitHub account @Issif ?

I'm afraid this has to be `falcosecurity` but I can push images manually after each release, it's not a big deal. I did it for current one.

For me, can close this issue, ok for you @fntlnz ?
