### ISSUE TITLE
When elasticsearch use custom certificate will lead to failure

### ISSUE THREAD

**Issue by xiaochen-2050** [falcosecurity/falcosidekick#344]
Describe the bug
When es url prefix `https` url.parse method is failed use the custom CA
x509: certificate signed by unknown authority

https://github.com/falcosecurity/falcosidekick/blob/4aa56d3841c7345300a18e99e8b1de32351e4572/outputs/elasticsearch.go#L28

Expected behaviour
ignore the ssl check when specific `checkcert: false`

**Comment by zhiweiv** [comment]
@xiaochen-2050 
Does this work for you now?
