### ISSUE TITLE
Update Loki endpoint and json format

### ISSUE THREAD

**Issue by sboschman** [falcosecurity/falcosidekick#351]
**Motivation**

Currently falcosidekick uses the deprecated Loki `/api/prom/push` endpoint (https://grafana.com/docs/loki/v2.6.x/api/#post-apiprompush). Might be a good idea to switch to the new Loki `/loki/api/vi/push` endpoint (https://grafana.com/docs/loki/v2.6.x/api/#push-log-entries-to-loki), including the new json format, before the old endpoint is dropped.

**Feature**

Switch Loki endpoint and json message format to the `/loki/api/v1/push` endpoint. I believe this endpoint has been available since Loki v1.0.0. Anyways, the oldest documentation on the site is for v1.6.x (https://grafana.com/docs/loki/v1.6.x/api/#post-lokiapiv1push), which has the endpoint. Loki v1.6.0 was released on 13 Aug 2020, so imho support for the old endpoint can just be dropped.

**Alternatives**

Assume Loki never drops this deprecated endpoint 😨 

**Additional context**

**Comment by Issif** [comment]
Hi,

The PR #309 introduced the possibility to set the URI for Loki endpoint, I agree it's time to use `/loki/api/v1/push` as default and the JSON format (much easier to debug). For avoiding to break things for users with old Loki servers, I'll add a option to choose the event format, just in case.

**Comment by Issif** [comment]
I finally decided to deprecate the old format for the new one, as it's there for a while. It seems to be ok in my last tests:
![image](https://user-images.githubusercontent.com/4520100/186162375-1a0bdc5a-63c5-49af-90bf-d457bb6e11df.png)

**Comment by Issif** [comment]
It will be released with next version :+1:
