### ISSUE TITLE
Optional `output` field?

### ISSUE THREAD

**Issue by pirxthepilot** [falcosecurity/falcosidekick#370]
**Motivation**

In an effort to make events coming from Falco as compact as possible, I would like to set [`json_include_output_property`](https://github.com/falcosecurity/falco/blob/master/falco.yaml#L84) to `false`. However, it looks like falcosidekick does not accept events that do not have the `output` field ([here](https://github.com/falcosecurity/falcosidekick/blob/master/types/types.go#L15) and [here](https://github.com/falcosecurity/falcosidekick/blob/master/handlers.go#L43-L50)).

**Feature**

Would it be possible for falcosidekick to accept events that do not have the `output` field? Thanks!

**Comment by Issif** [comment]
You're right, these fields are mandatory, what's your use case exactly? Even with them, the size of the payload is quite small and these fields are really useful for a lot of systems (eg response engine)

**Comment by pirxthepilot** [comment]
Hi Thomas, our falco config is generating a lot of events (on purpose) and so every bit of savings in the message size helps. The messages ultimately end up in a SIEM where only `output_fields` is used, aside from the rule name, priority and timestamp, so we really do not need `output`. We also have a few rules where we collect a lot of fields so the output can get quite big. And if falco itself supports not having the output field, I'm hoping sidekick can support it too.

Thanks!

**Comment by Issif** [comment]
reopen
/remove-lifecycle rotten
