### ISSUE TITLE
400 Headers Missing When Firing Multiple Alerts via HTTP Post

### ISSUE THREAD

**Issue by bc-sb** [falcosecurity/falcosidekick#375]
**Describe the bug**
When testing the falco/spyderbat integration we were seeing 400's header missing

**How to reproduce it**
setup a simple http service with a nonzero delay and a required header and point the webhook integration at it and fire 2 test events

**Expected behaviour**
200 responses for both request

**Screenshots**
```
2022/10/25 15:51:50 [INFO]  : Webhook - Post OK (200)
2022/10/25 15:51:51 [ERROR] : Webhook - header missing (400): {"message":"Failed to get expected header"}
2022/10/25 15:51:51 [ERROR] : WebHook - header missing
```

**Environment**
Saw first in aws hosted kubernetes, but able to reproduce locally

- Falco version:
```
GitVersion:    2.26.0-36-g76a29e9-dirty
GitCommit:     76a29e9f15dff55c9019d8ba1f9e8dee75c4da50
GitTreeState:  dirty
BuildDate:     '2022-10-21T11:45:18Z'
GoVersion:     go1.19.1
Compiler:      gc
Platform:      linux/amd64
```

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

Kubernetes helm chart and local build from source

**Additional context**

**Comment by Issif** [comment]
I'm not sure the Lock solved the issue after all, I'm updating the Loki output to work with Grafana Logs (SaaS), and I'm facing this issue:

```
2022/11/02 12:47:48 [ERROR] : Loki - authentication error (401): {"status":"error","error":"authentication error: no credentials provided"}
2022/11/02 12:47:48 [ERROR] : Loki - authentication error
2022/11/02 12:47:48 [INFO]  : Loki - Post OK (204)
2022/11/02 12:47:48 [INFO]  : Loki - Post OK (204)
```

**Comment by bc-sb** [comment]
It might need a refactor at this point. It seems like because there are 2
methods that can manipulate the headers there is definitely a non zero
chance one might beat the other. Wondering if the post call can accept the
headers and just do it locally in scope. If you move the lock unlock into
the Loki client I assume it fixes it?

**Comment by Issif** [comment]
Yes, your first solution by locking at output level seems the only way for now. Sorry for having led you in a wrong direction.

**Comment by Issif** [comment]
@bc-sb can you submit a new PR or do you want me to do it?

**Comment by bc-sb** [comment]
@Issif sorry...last week got away from me...so you want the original version I posted put up for PR?  If so, I can certainly quickly get that done.
