### ISSUE TITLE
Support  Common Event Format (CEF) format

### ISSUE THREAD

**Issue by aboe76** [falcosecurity/falcosidekick#382]
**Motivation**

To make it easier to integrate falco and microsoft sentinel I would like to be able to output
falco as CEF formatted messages. This make is also possible to connect/integrate falco with 
more security related products wich already support CEF.
- centrify
- arcsight
- splunk

**Feature**

CEF output looks like syslog but is formated differently. Microsoft Sentinel supports
protocol - tcp
port - 514 or localhost 25226
Format - CEF
TLS  - configurable

more information about CEF: 
https://learn.microsoft.com/en-us/azure/sentinel/cef-name-mapping

**Additional context**

there are multiple go libraries that can help with this:
- https://github.com/pcktdmp/cef
- https://github.com/xoebus/ceflog

**Comment by Issif** [comment]
Hello,

This is interesting, if I understand correctly this [doc](https://learn.microsoft.com/en-us/azure/sentinel/connect-common-event-format) and you, it's just replicate the syslog output but format the payload into the CEF format. I prefer to create a dedicated output for each solution, to have better metrics, even if the way to do in backend is same. Thank you, I'll dig deeper asap.

**Comment by aboe76** [comment]
This looks nice 👍,  yes I think you can add key Values, and some examples from the Microsoft page will tell you if they can automatically recognized

**Comment by aboe76** [comment]
@Issif can you give me an indication when 2.27.0 will be released?

**Comment by aboe76** [comment]
No worries, thanks for the update!


Op ma 9 jan. 2023 11:31 schreef Thomas Labarussias ***@***.***

**Comment by Issif** [comment]
@aboe76 The 2.27.0 is out, and the helm charts are updated https://falco.org/blog/falcosidekick-2-27-0-ui-2-1-0/

**Comment by aboe76** [comment]
Thank you for the notice.

Op di 10 jan. 2023 16:54 schreef Thomas Labarussias <
***@***.***>:
