### ISSUE TITLE
Fix error handling AWS Security Lake with `memlog` usage

### ISSUE THREAD

**Issue by embano1** [falcosecurity/falcosidekick#389]
As the maintainer of `memlog` I am happy you are using my package! Actually found out incidentally while checking importers of the package. Went through the code and IMHO there are some minor corrections or clarifications needed for the error handling logic in:

https://github.com/falcosecurity/falcosidekick/blob/41d530807f1a0294c0276e4cb42af68c8b26a659/outputs/awssecuritylake.go#L196-L227

For example, this line feels redundant as `Write()` never throws "future offset" - can be simplified: `if err.Error() != "future offset"`

Also, I recommend using `errors.Is(err, memlog.Err<Type>)` instead of string assertions.

`if count > 0` ignores error cases where `count == 0`.

I am happy to provide a PR, just wanted to better understand the error handling code from the author @Issif

**Comment by Issif** [comment]
Thanks for your comments. I'll be happy to review a PR from you to fix my silly mistakes  👍
