### ISSUE TITLE
Configurable сustom HTTP header for external integrations (Loki, Grafana, etc.)

### ISSUE THREAD

**Issue by ir0njaw** [falcosecurity/falcosidekick#401]
**Motivation**

My Loki instance is behind a proxy that requires a custom header for authentication before forwarding the request to Loki. The current implementation of Falcosidekick does not allow adding a custom header to the request.

**Feature**

Allow users to configure the custom HTTP Header for various external integrations, in particular Loki.

for example: 
`--set falcosidekick.config.loki.customHeader="X-token: 12345"`

```
POST /loki/api/v1/push HTTP/1.1
Host: 1.2.3.4:3100
User-Agent: Falcosidekick
X-token: 12345
Content-Length: 532
Content-Type: application/json
Accept-Encoding: gzip
```

**Comment by Issif** [comment]
Nice idea, I will work on that asap

**Comment by Issif** [comment]
I will not consider the pure SAAS outputs or not HTTP protocol, here's the list of outputs that could benefit new headers:

- Rocketchat
- Mattermost
- InfluxDB
- Alertmanager
- Elasticsearch
- Loki
- Grafana
- NodeRed
- CloudEvents
- Kafka REST
- OpenFAAS
- WebUI
- Zincsearch
- Gotify
- Tekton

It's a lot, I'll focus on few as nobody else requested this feature for now:

- Loki
- Grafana
- Elasticsearch

Is that ok for you?
