### ISSUE TITLE
PolicyReport API / Client Update

### ISSUE THREAD

**Issue by fjogeleit** [falcosecurity/falcosidekick#402]
**Describe the bug**

Not really a bug, more a cleanup. Falcosidekick uses the PolicyReport API/Client from the kube-bench-adapter which no longer maintain its own copy, instead using the provided api and client code from the Kubernetes Policy Working Group.

This should be aligned by removing the dependency to kube-bench-adapter and using the wg api/client code as well.

**Comment by Issif** [comment]
We can close this issue, I updated the whole deps for this output weeks ago
