### ISSUE TITLE
falcosidekick to grafana loki: hostname label - need additional details

### ISSUE THREAD

**Issue by jodanpotasu** [falcosecurity/falcosidekick#469]
I tried lurk the sidekick code athough it didn't help much..
I have a problem with the **hostname**. I have a couple of servers running where each one has falco running in the docker. Of course I have changed the hostname in each docker, but still I am being sent a string of characters that I cannot decrypt.

What i have on machine: ansible-test
What i have in docker container: ansible-test-docker
What sidekick sends as hostname: ff5809b3eaba

Could someone please tell me how to change the hostname that sidekick sends or how to decrypt it?

![image](https://user-images.githubusercontent.com/17862475/235484525-0c81c78c-b72e-475e-85fc-c8ba68c4d7ea.png)

**Comment by Issif** [comment]
Hi,

The  `hostname` field is not filled by Falcosidekick but by Falco itself, it's the name of host/container where Falco is running. I guess you could make Falcosidekick override the value with the [`custom fields`](https://github.com/falcosecurity/falcosidekick/blob/2ffcd83b0894e35c6def55f88e915c6ca6a9fafc/config_example.yaml#L4

**Comment by jodanpotasu** [comment]
@Issif thank you for the answer! 
Unfortunately I need to know which node the request comes from, overriding in this case will not work, or maybe I do not see the idea :(

**Comment by Issif** [comment]
What kind of installation do you have? In K8s? Direct on host?

**Comment by Issif** [comment]
If falco run at host level, the `hostname` field should be the hostname of your host, except you run falco in a container. Can you check the hostname is correctly set?

**Comment by jodanpotasu** [comment]
that's hostname directly in vm
![image](https://user-images.githubusercontent.com/17862475/235723299-3b767f7a-9357-4b85-9735-170479b8415f.png)
Second one is from docker 
![image](https://user-images.githubusercontent.com/17862475/235723436-f24ba8b2-9d14-42fd-9717-783fa4c1740f.png)

**Comment by Issif** [comment]
I don't understand why falco doesn't use that values.

Question: I see you're in fluent-bit folder, are you using it to forward the falco events to loki? if true, why are you using falcosidekick?

**Comment by jodanpotasu** [comment]
@Issif I would like to really apologize to you. Totally stupid mistake resulted.

I have two nodes, only one should work, but unfortunately the other one was launched by cron and all the logs I saw on grafana came from the other one (with an invalid hostname).

I don't use fluent-bit to send events to loki. Falcosidekick gives me more flexibility. This folder was already open in the tab ;)

**Comment by Issif** [comment]
No problem, as long we figured out how to fix your issue, it's ok :+1:
