### ISSUE TITLE
publish docker image

### ISSUE THREAD

**Issue by palmerabollo** [falcosecurity/falcosidekick#47]
Hi @Issif . Could you please push the 2.10.0 image to docker hub when you have some time?
Thanks.

**Comment by Issif** [comment]
@palmerabollo I forgot, sorry. 

It's pushed : [2.10.0](https://hub.docker.com/layers/falcosecurity/falcosidekick/2.10.0/images/sha256-d9b2e10b6ea0025a57d4e00b2f8b35a917e676b18c8156833558f45fad8053b3)

Thanks.
