### ISSUE TITLE
FalcoSideKick Alertmanager include "description" annotation

### ISSUE THREAD

**Issue by msalman899** [falcosecurity/falcosidekick#477]
Hello, 

it would be convenient if we can add "description" annotation as well for falcosidekick alert manager forwarder.

**Comment by Issif** [comment]
Hi,

Can you elaborate what you call "description" please. If you refer to the description field in the rules, is only there for the humans to understand the rules and they are not part of the alerts from Falco.

**Comment by msalman899** [comment]
I think it should be simple by adding this line [here](https://github.com/falcosecurity/falcosidekick/blob/master/outputs/alertmanager.go#LL84C1-L84C1)

`amPayload.Annotations["description"] = falcopayload.Output`

**Comment by Issif** [comment]
OK I see what you mean now. I'll create a PR to add this annotation.
