### ISSUE TITLE
 Error: failed to generate container "***" spec: failed to generate spec: no command specified

### ISSUE THREAD

**Issue by mugambika** [falcosecurity/falcosidekick#486]
Trying to install Falcosidekick on rke2 version 1.24.9+rke2r2. We are observing the following errors:
Falcosidekick:
 Error: failed to generate container "***" spec: failed to generate spec: no command specified

Falcosidekick-ui:

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Issif** [comment]
duplicate with #487
