### ISSUE TITLE
Additional configuration for Falco default rules on Alertmanager

### ISSUE THREAD

**Issue by HuyDo-95g** [falcosecurity/falcosidekick#493]
**Motivation**

Falco default rules are good but can't be modified individually.

**Feature**

I think it would make sense to allow user to modify an individual Falco default rule that are send to Alertmanager to match with user's usage or business without have to replace the whole list of default rule to user's customized rules.
For example:

- change "priority: Critical" to "severity: Critical"
- Add additional description for different rule.

**Alternatives**

At the moment user only could add an extra label or extra annotation to the whole list of default rule but not an individual one.

**Additional context**

**Comment by Issif** [comment]
Hi,

For the mapping between severity and priority, there's already the PR #440 for that.
For your second point, I don't understand your usage. If you want different format for the alerts, you have to change the `output` field in falco's rules.

**Comment by HuyDo-95g** [comment]
Hi @Issif,
Thanks for your quick response. 
Does any falcosecurity chart support to change the falco's rules output? And is it possible to change the output of individual rule?

**Comment by Issif** [comment]
The release 2.29.0 fixed this issue.
