### ISSUE TITLE
PagerDuty Europe URL

### ISSUE THREAD

**Issue by PaulPowershell** [falcosecurity/falcosidekick#496]
Feature :
I would like to request the addition of a feature that allows users to select and utilize the PagerDuty Europe instance (.eu.pagerduty.com) within the application. This feature would enable European users to access and manage their incidents and alerts through the European instance, providing them with a localized experience and complying with data privacy regulations.

Alternatives :
As an alternative, users could manually modify the application's codebase to replace the default PagerDuty instance with the European instance. However, this approach would require technical expertise and ongoing maintenance to ensure compatibility with future updates. Having a built-in feature to switch between instances would be more user-friendly and provide a seamless experience.

example :
pagerduty:
  routingKey: "" # Pagerduty Routing Key, if not empty, Pagerduty output is enabled
  minimumpriority: "" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
  Europe: "true" # Default false

**Comment by Issif** [comment]
Good idea, it was not available when I developed the output. Let me create the PR.

**Comment by Issif** [comment]
The PR has been approved, the feature will be available in the next release 2.28.0. I don't have any ETA yet, sorry.

**Comment by PaulPowershell** [comment]
so fast! thank you so much
