### ISSUE TITLE
Add the option to deploy TLS or mTLS server instead of the HTTP Server

### ISSUE THREAD

**Issue by annadorottya** [falcosecurity/falcosidekick#507]
**Motivation**

Currently only HTTP server can be deployed. It would be more secure if we could deploy TLS or mutualTLS server if wanted.

**Feature**

An option in the config to enable TLS and mTLS and ability to set the path for necessary cert files.

**Alternatives**

**Additional context**

**Comment by Issif** [comment]
I agree, but a lot relies on Falco. I would like an auth mechanism too, to avoid the injection of fake events. I'll take a look at your PR.

**Comment by annadorottya** [comment]
Thank you! Related issue on Falco's side: https://github.com/falcosecurity/falco/issues/2632
