### ISSUE TITLE
[SLACK Integration]: Message Format Interpolation Failure

### ISSUE THREAD

**Issue by kamirendawkins** [falcosecurity/falcosidekick#52]
**Describe the bug**
As documented the message formatting works as expected:
```yaml
messageformat: "Alert : rule *{{ .Rule }}* triggered by user *{{ index .OutputFields \"user.name\" }}*"
```

In an attempt to be more dynamic it appears that interpolation completely fails:

```yaml
messageformat: "*{{ index.OutputFields \"priority\"}}* : rule *{{ .Rule }}* triggered by user *{{ index .OutputFields \"user.name\" }}*"
```

**How to reproduce it**

Pass in the above Slack Message Formatting and test. Using the above format will remove all format text and logging will not indicate a failure.

**Expected behaviour**

Since we can pull selected fields into the message format normally I expected that instead of hard coding alert we could instead get Warning/Critical/Alert etc.

**Screenshots**
<img width="664" alt="Screen Shot 2019-12-11 at 7 56 27 AM" src="https://user-images.githubusercontent.com/19929464/70623305-d26f5e80-1beb-11ea-961a-bbb219a939b1.png">

**Environment**

- Falco version:
Falco version: 0.17.1
- System info:
```json
{
  "machine": "x86_64",
  "nodename": "qa-kare-falco-xblfq",
  "release": "4.14.146-119.123.amzn2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Sep 23 16:58:43 UTC 2019"
}
```
- Cloud provider or hardware configuration:
- OS:
```bash
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel:
```bash
Linux falco-xblfq 4.14.146-119.123.amzn2.x86_64 #1 SMP Mon Sep 23 16:58:43 UTC 2019 x86_64 GNU/Linux
```
- Installation method:

Falco: Kubernetes Upstream Helm Chart
Sidekick: Kubernetes Upstream Helm Chart
**Additional context**

**Comment by Issif** [comment]
Your example is wrong. It should be :

```yaml 
messageformat: "*{{ \"priority\"}}* : rule *{{ .Rule }}* triggered by user *{{ index .OutputFields \"user.name\" }}*"
```

With that payload (from README example) :

```json
{"output":"16:31:56.746609046: Error File below a known binary directory opened for writing (user=root command=touch /bin/hack file=/bin/hack)","priority":"Error","rule":"Write below binary dir","time":"2019-05-17T15:31:56.746609046Z","output_fields":{"akey":"A Value","evt.time":1507591916746609200,"fd.name":"/bin/hack","proc.cmdline":"touch /bin/hack","user.name":"root"}}
```

![image](https://user-images.githubusercontent.com/4520100/70632066-7548cc80-1c2e-11ea-84ef-021bcdf6d0ad.png)


`priority` is not a part of `output_fields` (`OutputFields` in `Go struct`).

If you want to access a value from its key in `OutputFields`, this works :

```yaml
messageformat: "*{{ index .OutputFields \"fd.name\"}}*"
```

![image](https://user-images.githubusercontent.com/4520100/70632162-990c1280-1c2e-11ea-9fb1-56240ebedfa3.png)

**Comment by kamirendawkins** [comment]
@Issif For some reason I had thought that priority was part of the struct but I see that it is indeed not. Sorry about that. I will close this since it is not actually an issue.

**Comment by Issif** [comment]
No problem, this issue may be useful for some else in future.
