### ISSUE TITLE
Falcosidekick not create topic into Kafka automatically

### ISSUE THREAD

**Issue by victorrodriguez1984** [falcosecurity/falcosidekick#546]
**Motivation**

**Feature**

**Alternatives**

**Additional context**
FalcoVersion: 0.34.0 helm.sh/chart: falco-3.0.0
SideckickVersion: 2.27.0  helm.sh/chart: falcosidekick-0.5.16

**Comment by Issif** [comment]
I checked the lib used for kafka, the writer has the option ` AllowAutoTopicCreation`, we can use it to create the topic automatically.

**Comment by Issif** [comment]
The PR for has been merged
