### ISSUE TITLE
falcosidekick cannot be deployed on k8s with Pod Security Policy enabled

### ISSUE THREAD

**Issue by czunker** [falcosecurity/falcosidekick#55]
**Describe the bug**

The helm chart does not contain a pod security policy, a clusterrole and an assignment.

**How to reproduce it**

Try to deploy it in k8s with PSPs enabled.

**Expected behaviour**

helm charts deployes without errors. and pod starts.

**Screenshots**

**Environment**

- Falco version:
0.18.0
- System info:

- Cloud provider or hardware configuration:
AWS
- OS:
kops based k8s with falcosidekick container
- Kernel:

- Installation method:

**Additional context**

**Comment by czunker** [comment]
The combination of #53 and #54 should fix the problem.

**Comment by Issif** [comment]
I approved your two PR. I will release 2.11.2 soon. Thanks.

**Comment by Issif** [comment]
[2.12.0](https://github.com/falcosecurity/falcosidekick/releases/tag/2.12.0)
