### ISSUE TITLE
Falcosidekick image 'falcosecurity/falcosidekick' published with 99.99.99 tag.

### ISSUE THREAD

**Issue by b-abderrahmane** [falcosecurity/falcosidekick#556]
I use [Renovate](https://github.com/renovatebot/renovate) to maintain some Kubernetes manifests and it opened a PR for bumping the docker image version of falcosidekick from 2.27 to [99.99.99 ](https://hub.docker.com/layers/falcosecurity/falcosidekick/99.99.99/images/sha256-0992ddb90c92d14808858bd034b6a9d3d6ab90310a9955130af453ea2c24853b?context=explore)
My assumption here is that this tag was published by mistake or as part of some test run? If so can someone remove it since it can be confusing both for end-users as well as for dependency management software.

Thank you.

**Comment by Issif** [comment]
Hi,

Sorry for this. We recently revamped the Github Actions workflow to add signature and SBOM to all images. This "fake" version has been created to test it, we removed the artifacts in Github but forgot to remove the resulting images on Dockerhub. I don't have the right to delete tags myself on Dockerhub, I requested some help from the other maintainers.
