### ISSUE TITLE
Add option to deploy a HTTP server for the metrics endpoint

### ISSUE THREAD

**Issue by annadorottya** [falcosecurity/falcosidekick#564]
**Motivation**

I want to use [GKE Managed Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus) to get the data from falcosidekick's `/metrics` endpoint. I also want to use the TLS server option. 
However I ran into the issue that the Prometheus server wants to authenticate the falcosidekick server based on IP address, and the certificate can't be issued for that.
One solution would be to tell Prometheus to skip verification, there is an issue for that opened a year ago: https://github.com/GoogleCloudPlatform/prometheus-engine/issues/238
Until that issue is closed, the other solution is deploying an HTTP server on falcosidekick for the /metrics endpoint.

**Feature**

Add option in configuration to deploy a HTTP server serving the metrics endpoint. Example config:
```
tlsserver:
  metricshttp: false # if true, a separate http server will be deployed for the Prometheus metrics endpoint
  metricsport: 2802 # port to serve metrics http server if deployed (default: 2802)
```

**Alternatives**

I was wondering if serving only the `/metrics` endpoint is enough or serving all of the endpoints on HTTP as well would make more sense. (Is there a use case for that?)

**Additional context**

**Comment by Issif** [comment]
I don't understand your alternative, using http for all endpoints, it's pretty much the default behaviors til now. I think anyway, we could have more endpoints without TLS even when it's enabled, for example `/healthz`.

My proposal is a bit different so. I would prefer something like:
```yaml
tlsserver:
  notlsport: 2810
  notlspaths:
    - /metrics
    - /healthz
```
To list the paths to exclude from TLS, if the list != empty, we start the httpserver aside with the port `notlsport`.

Anyway, you can't reuse the port 2802 as it's already mapped to the webserver with TLS.

WDYT

**Comment by annadorottya** [comment]
For alternative I meant that all the endpoints are served on HTTP on the second port while the TLS server also runs.
But your proposal is more flexible, I'll make the updates soon according to it and also change the default port to 2810.

**Comment by Issif** [comment]
Having all endpoints responding to TLS and non-TLS at same time destroys the whole logic to have a secured connection. Keep me updated, I'm releasing the 2.28.0 in few days.
