### ISSUE TITLE
Sidekick didn't enable kafka output

### ISSUE THREAD

**Issue by EdikAndriasyan** [falcosecurity/falcosidekick#572]
I have deployed sidekick in kubernetes cluster with helm( chart version:0.6.2, app version:2.27.0 ). I am enabling the following sidekick outputs.
- Elasticsearch
- Slack
- Kafka

Elasticsearch and slack are working properly but sidekick is not enabling kafka output. Here is the configuration part.

```
config:
  existingSecret: ""
  extraEnv: []
  debug: false
  customfields: "from:falcosidekick"
  templatedfields: ""

  elasticsearch:
    hostport: "http://server1:9200" # http://{domain or ip}:{port}, if not empty, Elasticsearch output is enabled
    index: "falco" # index (default: falco)
    type: "_doc"
    minimumpriority: "" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
    suffix: "daily" # date suffix for index rotation : daily (default), monthly, annually, none
    mutualtls: false # if true, checkcert flag will be ignored (server cert will always be checked)
    checkcert: false # check if ssl certificate of the output is valid (default: true)
    username: "elastic" # use this username to authenticate to Elasticsearch if the username is not empty (default: "")
    password: "ES_PASSWORD" # use this password to authenticate to Elasticsearch if the password is not empty (default: "")
    customHeaders: # Custom headers to add in POST, useful for Authentication
      key: value
      
  kafka:
    hostport: "server1:9092,server2:9092,server3:9092"
    topic: "test.topic"
    sasl: ""
    username: ""
    password: ""
    # -- produce messages without blocking
    async: false
    requiredacks: "1"
    compression: "GZIP"
    balancer: "round_robin"
    # -- specify a client.id when communicating with the broker for tracing
    clientid: ""
    # -- minimum priority of event to use this output, order is `emergency\|alert\|critical\|error\|warning\|notice\|informational\|debug or ""`
    minimumpriority: ""

  slack:
    webhookurl: "SLACK_WEBHOOK"
    channel: "#falco"
    footer: ""
    icon: ""
    username: "Falco"
    # -- `all` (default), `text` (only text is displayed in Slack), `fields` (only fields are displayed in Slack)
    outputformat: "all"
    # -- minimum priority of event to use this output, order is `emergency\|alert\|critical\|error\|warning\|notice\|informational\|debug or ""`
    minimumpriority: ""
    # -- a Go template to format Slack Text above Attachment, displayed in addition to the output from `slack.outputformat`. If empty, no Text is displayed before Attachment
    messageformat: ""
```

Here is the log of sidekick.

<img width="603" alt="Screenshot 2023-07-26 at 12 54 22" src="https://github.com/falcosecurity/falcosidekick/assets/87753717/ce89f11f-4faf-4e4e-8fc5-3fa1e941496d">

**Comment by ibice** [comment]
Hi @EdikAndriasyan, have you tried specifying just one server?

```diff
  kafka:
-    hostport: "server1:9092,server2:9092,server3:9092"
+    hostport: "server1:9092"
    topic: "test.topic"
```

**Comment by EdikAndriasyan** [comment]
> 

Hi @ibice, thank you for quick response. Yes the same picture.

**Comment by ibice** [comment]
`requiredacks` needs to be a one of `all`, `one` or `none` (case-insensitive). `1` isn't a valid value. Source:
https://github.com/falcosecurity/falcosidekick/blob/4d11678483cf3cd4703f50f54a69c76a778163ac/outputs/kafka.go#L103-L112

Changing it to one should fix your problem:

```diff
  async: false
-  requiredacks: "1"
+  requiredacks: "one"
  compression: "GZIP"
```

**Comment by EdikAndriasyan** [comment]
Thank you so much for your valuable assistance; it has been really helpful. However, I have another concern. As I understand it, specifying an unsupported value will result in the error mentioned in defaults( which I didn't receive ). Additionally, I believe the error message might display config.Kafka.RequiredACKs instead of config.Kafka.Compression.

**Comment by ibice** [comment]
You're right! But that error message doesn't get printed by the caller. That's why you didn't see it in your logs.

https://github.com/falcosecurity/falcosidekick/blob/4d11678483cf3cd4703f50f54a69c76a778163ac/main.go#L446-L449

I would also expect that errors to get printed, but I'll leave that decision to the maintainers. It seems most of the errors returned by the output constructors are not printed, if not all.

**Comment by Issif** [comment]
> Thank you so much for your valuable assistance; it has been really helpful. However, I have another concern. As I understand it, specifying an unsupported value will result in the error mentioned in defaults( which I didn't receive ). Additionally, I believe the error message might display config.Kafka.RequiredACKs instead of config.Kafka.Compression.

Good catch, I'm fixing it.

**Comment by EdikAndriasyan** [comment]
Thank you guys for your quick response, closing the issue!!!

**Comment by Issif** [comment]
FYI, the multiple hosts will come with the next version of falcosidekick, in few days.
