### ISSUE TITLE
Error message on testing the binary upon building

### ISSUE THREAD

**Issue by danielcabezas80** [falcosecurity/falcosidekick#611]
After building the falcosidekick binary, the default testing command issues an error. No output is generated

After build, tried the command provided in the github webpage:

```
curl "http://localhost:2801/" -d'{"output":"16:31:56.746609046: Error File below a known binary directory opened for writing (user=root command=touch /bin/hack file=/bin/hack)","priority":"Error","rule":"Write below binary dir","time":"2019-05-17T15:31:56.746609046Z", "output_fields": {"evt.time":1507591916746609046,"fd.name":"/bin/hack","proc.cmdline":"touch /bin/hack","user.name":"root"}}'
```

The message output is:

```
boxuser@ubuntu-docker:~/falcosidekick$ ./falcosidekick 
2023/08/30 14:26:40 [INFO]  : Falco Sidekick version: devel
2023/08/30 14:26:40 [INFO]  : Enabled Outputs : [Slack]
2023/08/30 14:26:40 [INFO]  : Debug mode : true
2023/08/30 14:26:40 [DEBUG] : running HTTP server
2023/08/30 14:26:40 [INFO] : Falco Sidekick is up and listening on :2801
2023/08/30 14:27:39 http: panic serving 127.0.0.1:43408: inconsistent label cardinality: expected 5 label values but got 4 in prometheus.Labels{"k8s_ns_name":"", "k8s_pod_name":"", "priority":"Error", "rule":"Write below binary dir"}
goroutine 16 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x22af7c0, 0xc000616de0})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/prometheus/client_golang/prometheus.(*CounterVec).With(...)
	/home/vboxuser/Projects/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/counter.go:286
```

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:
boxuser@ubuntu-docker:~$ falco --version
Wed Aug 30 14:40:23 2023: Falco version: 0.35.1 (x86_64)
Wed Aug 30 14:40:23 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Falco version: 0.35.1
Libs version:  0.11.3
Plugin API:    3.0.0
Engine:        17
Driver:
  API version:    4.0.0
  Schema version: 2.0.0
  Default driver: 5.0.1+driver

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Issif** [comment]
Sorry for the delay, I was on holidays.

Can you paste your configuration please (obfuscate or omit the slack webhook), please.

**Comment by Issif** [comment]
I found the root cause, the example is obsolete, the falco payload has now a field `hostname` which is used as prometheus label.

This command should run as expected:

```
curl -XPOST "http://localhost:2801/" -d'{"hostname": "localhost", "output":"16:31:56.746609046: Error File below a known binary directory opened for writing (user=root command=touch /bin/hack file=/bin/hack)","priority":"Error","rule":"Write below binary dir","time":"2019-05-17T15:31:56.746609046Z", "output_fields": {"evt.time":1507591916746609046,"fd.name":"/bin/hack","proc.cmdline":"touch /bin/hack","user.name":"root"}}'
```

I will create a fix anyway.
