### ISSUE TITLE
Add quickwit as a log output

### ISSUE THREAD

**Issue by fmassot** [falcosecurity/falcosidekick#640]
Looking at the available outputs, it should be easy to add [quickwit](https://github.com/quickwit-oss/quickwit/).

I will give it a try.

**Comment by Issif** [comment]
hi @fmassot,

are you still working on that topic? thanks

**Comment by fmassot** [comment]
I don't have the time; @idrissneumann might want to give it a try; can you give us some hints to get started?

**Comment by Issif** [comment]
I see Quickwit provides a basic JSON API, you can take a look at the [`webhook`](https://github.com/falcosecurity/falcosidekick/blob/master/outputs/webhook.go) output to replicate

**Comment by idrissneumann** [comment]
Hi hello. Now I have finished my tasks on the Grafana datasource plugin for quickwit, I'll take a look tomorrow :)

I might come back with some questions :D

Thanks!

**Comment by Issif** [comment]
I'm AFK for few days, but I can still answer to your questions here. Thanks for your help

**Comment by idrissneumann** [comment]
Work in progress here: https://github.com/falcosecurity/falcosidekick/pull/736
