### ISSUE TITLE
Make the Helm chart available in Helm Hub

### ISSUE THREAD

**Issue by arminc** [falcosecurity/falcosidekick#67]
**Motivation**

It would make sense to make the chart release so it can be available in the Helm Hub. This allows the project to be used without needing the GitHub project or having to copy the current deployment Helm files in this repo.

**Feature**

Chart available in Helm Hub.

**Comment by Issif** [comment]
Hi @arminc 

I agree the helm chart could (should) be outside that repo, even if it's convenient for me for maintenance.

Maybe you don't know, but we decided to extract falc helm chart from hub lately, the up to date version is now here : https://github.com/falcosecurity/charts

To keep a coherance, I prefer to use this repo for falcosidekick too.

**Comment by arminc** [comment]
Just to be clear I didn't ment to add the chart to https://github.com/helm/charts/tree/master/stable. It is fine to keep the chart in this repo but it should be released, like the Falco chart so it can be used directly with helm. But it stil makes sense to add the Helm chart repo to http://hub.helm.sh so it is easier to be found

**Comment by leogr** [comment]
Since https://github.com/falcosecurity/charts has been included in the Helm Hub ( see https://github.com/helm/hub/pull/409 ), once this chart is moved to https://github.com/falcosecurity/charts then it will be automatically listed on the hub.

**Comment by Issif** [comment]
@nibalizer is working on a new output, `Discord`, when it will be merged, I will release a new version of `falcosidekick` and according helm chart will be in the global repository

**Comment by Issif** [comment]
@arminc enjoy : https://hub.helm.sh/charts/falcosecurity/falcosidekick
