### ISSUE TITLE
Azure Event Hub support for Workload Identity

### ISSUE THREAD

**Issue by jackmtpt** [falcosecurity/falcosidekick#683]
**Motivation**

- Falco Sidekick is using a deprecated library (azure-event-hubs-go) to connect to Azure Event Hubs
- This doesn't seem to support Workload Identity, only the old/unsupported Pod Identity
- https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/README.md is apparently the new library to use which supports Workload ID.

**Feature**

AKS Workload Identity should be supported.

**Comment by Issif** [comment]
Hi,

Thanks for this issue, I didn't know, cause I'm not an Azure user. If you feel confident enough, you can propose a PR and I will review it anyway.

Thanks

**Comment by jackmtpt** [comment]
/remove-lifecycle stale

I'm not a Go developer so I won't be able to contribute a PR but the issue should not be marked as stale.

**Comment by adamshawvipps** [comment]
We are trying to run falco in AKS and would like this. feature Is there any date set to release the [updates  ]?(https://github.com/falcosecurity/falcosidekick/commit/82371a7574b029977b59ae52fdb73adbe261043e#diff-99ac4f00326baa9cce20c3f05824a1366266236affcdbdde3fe5b5356e654770) @Issif

**Comment by Issif** [comment]
> We are trying to run falco in AKS and would like this feature. Is there any date set to release the [updates ](https://github.com/falcosecurity/falcosidekick/commit/82371a7574b029977b59ae52fdb73adbe261043e#diff-99ac4f00326baa9cce20c3f05824a1366266236affcdbdde3fe5b5356e654770) @Issif

I recently updated all deps for Azure but I didn't tested them, any help is welcome as I'm not familiar with AKS. Basically, by using the `latest` tagged image you should be able to test.

**Comment by Issif** [comment]
Will be fixed in the upcoming 2.29

**Comment by PowerSurj** [comment]
just wanted to check if the fix is actually present in the 2.29 or has the fix release been postponed?

**Comment by Issif** [comment]
The 2.29.0 is out and contains the fix, the helm charts are also updated, you can try the new version.

**Comment by kasunsjc** [comment]
I'm not sure helm chart was changed. Still see the old values using pod identity
![image](https://github.com/user-attachments/assets/4153da64-ffe4-4c7c-a6ef-1b630827a779)
