### ISSUE TITLE
OIDC Authentication for Alertmanager and Loki

### ISSUE THREAD

**Issue by dmolik** [falcosecurity/falcosidekick#712]
**Motivation**

I'm trying to push outputs to Alertmanager and Loki, but cross-cluster traffic is authenticated via Service Accounts in OIDC.

**Feature**

Support OIDC clients in both Loki and Alertmanager outputs. 

I'm happy to commit up a PR, but this is potentially a 'more involved' code change so I would like to discuss, scope and approach, and acceptance criteria.

**Comment by Issif** [comment]
You're right, it might imply a lot of changes, let me dig first

**Comment by dmolik** [comment]
Had a discussion out of band, long and short of it, going to try to extend the existing http client with OIDC auth instead of using the Loki or Alertmanager clients

**Comment by Issif** [comment]
You mean the http client shared between the different outputs? If you do so, it means more than Loki and AlertManager will have the benefit, so their configs must be adapted either.
