### ISSUE TITLE
Username configuration isn't picked up for Mattermost-Provider

### ISSUE THREAD

**Issue by DrunkenHomer** [falcosecurity/falcosidekick#730]
**Describe the bug**

Configuring the mattermost username doesn't change the values in the alert. Falcosidekick will instead always use "Falcosidekick" as username as it is hardcoded in line: https://github.com/falcosecurity/falcosidekick/blob/19813e277275a658961a203cbca109ee887aa6dc/outputs/mattermost.go#L130

**How to reproduce it**

Start Falcosidekick and configure the Mattermost username, e.g. using the env `MATTERMOST_USERNAME`

**Expected behaviour**

The notification uses the correct username and only defaults to "Falcosidekick" when no value is given.

**Environment**

- Falco version:
Falco: 0.36.2 and Falcosidekick 2.28.0

**Comment by Issif** [comment]
The PR #731 will fix that. Thanks for your report.
