### ISSUE TITLE
systemd wget not pulling latest download

### ISSUE THREAD

**Issue by cccsss01** [falcosecurity/falcosidekick#747]
**What to document**
wget https://github.com/falcosecurity/falcosidekick/releases/latest -O falcosidekick  

not pulling latest, getting web information

will likely need tar -xvf xyz included in the docs as well. right after the wget.

i'm not sure how to fix this, but can manually specify the package

**Comment by Issif** [comment]
fixed by #746
thanks @cccsss01

**Comment by Issif** [comment]
#754 fixed it.
