### ISSUE TITLE
Alertmanager output - Header missing (400)

### ISSUE THREAD

**Issue by epcim** [falcosecurity/falcosidekick#77]
**Describe the bug**

Alerts are not sent, not enough log details about actual bug. Additionally this raises we shall export prometheus metrics about recieved/sent events and health state, as suggested in: https://github.com/falcosecurity/falcosidekick/issues/60
```
2020/09/03 09:45:14 [ERROR] : AlertManager - Header missing (400)
2020/09/03 09:45:19 [ERROR] : AlertManager - Header missing (400)
2020/09/03 09:47:33 [INFO]  : AlertManager - Post OK (200)
2020/09/03 09:47:47 [ERROR] : AlertManager - Header missing (400)
2020/09/03 09:48:50 [ERROR] : AlertManager - Header missing (400)
2020/09/03 09:49:19 [ERROR] : AlertManager - Header missing (400)
```

Caused by:

```
level=error ts=2020-09-03T13:47:41.979Z caller=api.go:781 component=api version=v1 msg="API error" err="bad_data: \"proc_aname[2]\" is not a valid label name"
level=error ts=2020-09-03T13:48:14.139Z caller=api.go:781 component=api version=v1 msg="API error" err="bad_data: \"proc_aname[2]\" is not a valid label name"
```

Will provide MR with fix.

**Comment by Issif** [comment]
Ok I see the what issue it is. Will fix it asap if you don't.

**Comment by Issif** [comment]
Can we close this issue as #78 as been merged?

**Comment by epcim** [comment]
Yes, closePetr Michalec+420734420347petr@apealive.netOn 13 Sep 2020 21:11, Thomas Labarussias <notifications@github.com> wrote:
Can we close this issue as #78 as been merged?

**Comment by Issif** [comment]
👍
