### ISSUE TITLE
Add AWS Security Hub

### ISSUE THREAD

**Issue by Issif** [falcosecurity/falcosidekick#8]
https://docs.aws.amazon.com/fr_fr/securityhub/1.0/APIReference/Welcome.html

**Still in Preview at AWS**

**Comment by perriea** [comment]
In the Helm Chart (https://github.com/helm/charts/blob/master/stable/falco/values.yaml#L172), there is the Google Cloud Security Command Center, so it's possible to create an issue to ask a new integration with AWS.
