### ISSUE TITLE
Teams: Add field ordering

### ISSUE THREAD

**Issue by pentago** [falcosecurity/falcosidekick#800]
**Motivation**

Currently, Teams notifications are messy as there's no order at which fields are displayed regardless of the fact how they're listed in config.

Currently, I have one rule that results in notifications like these:
![image](https://github.com/falcosecurity/falcosidekick/assets/876756/4348b4c5-b88f-40e2-87d5-00871801652d)

**Feature**

At a minimum, display fields in a way that they're listed in a rule output.
What I have is:

```console
output: Container launched with root user privilege (evt_type=%evt.type user=%user.name user_uid=%user.uid user_loginuid=%user.loginuid kubernetes_namespace=%k8s.ns.name kubernetes_pod_name=%k8s.pod.name kubernetes_pod_id=%k8s.pod.uid kubernetes_pod_ip=%k8s.pod.ip container_name=%container.name container_image_registry=%container.image.repository container_image=%container.image container_image_tag=%container.image.tag container_image_digest=%container.image.digest container_image_id=%container.image.id container_is_privileged=%container.privileged container_uptime=%container.duration container_ip=%container.ip process=%proc.name proc_exepath=%proc.exepath parent=%proc.pname command=%proc.cmdline terminal=%proc.tty exe_flags=%evt.arg.flags)
```

**Alternatives**

Perhaps this is only Sidekick/Teams type deal, there's a chance `config.alertmanager` or direct `config.webhook` would work but I didn't check it out yet.

**Additional context**

possibly related to https://github.com/falcosecurity/falcosidekick/issues/223

**Comment by Issif** [comment]
Hi,

I see your point, I try to integrate a consistency in slack/mattermost/rocketchat because I had access to instances for my tests. For Teams, I don't have access to an instance anymore, but I can replicate what I did anyway. 

Basically, I will use that exact same order:
![image](https://github.com/falcosecurity/falcosidekick/assets/4520100/94eee32a-5849-49df-8a84-52cf7c85b824)

ok for you?

**Comment by Issif** [comment]
I see your point. I don't have access to a Teams anymore to be able to test a more complex formatting for the messages. I created anyway the PR #802, to enforce the same order of fields in more messaging systems. The tags and the output_fields will be alphabetically ordered. It means the `proc.*`, `k8s.*`, etc, will be more grouped.

**Comment by pentago** [comment]
Cool, thanks. It will work.

**Comment by Issif** [comment]
as #802 is merged, I'm closing this issue
