### ISSUE TITLE
GCP Bucket output does not write anything to bucket

### ISSUE THREAD

**Issue by mattdecorniquet** [falcosecurity/falcosidekick#809]
**Describe the bug**

I'm experiencing exactly the same issue described in #313 (which was fixed in #312):
I've configured credentials for a bucket in the GCS output section, the k8s cluster is generating logs and sending them to falco and then to falcosidekick.
The latter has the following in its logs `GCPStorage - Upload to bucket OK`, debug mode show the proper payload but nothing is created on the bucket.
Trying to output those same logs with a default loki config works flawlessly.

**How to reproduce it**

- Configure the GCP Bucket output in sidekick.
- Generate a debug event.
- Observe GCPStorage - Upload to bucket OK
- Observe no new objects or API calls in the target GCP bucket

**Expected behaviour**

Logs should be written in the target GCP bucket when falcosidekick says it uploaded successfully.

**Screenshots**
<img width="1122" alt="image" src="https://github.com/falcosecurity/falcosidekick/assets/103426136/d30fcba6-7516-4662-8de6-fde8fa106891">

**Environment**

GKE, 9 nodes on Google container-OS. Falco and falcosidekick both installed with official helm chart with sidekick.enabled=true.
We're using argocd to manage helm.

- Falco version:
helm chart is falco-4.2.2 so falco is 0.37.1 and falcosidekick is 2.28.0

**Additional context**

**Comment by Issif** [comment]
Thanks for this report. I didn't implemented the GCS output myself, I'll try to find some help.

**Comment by Issif** [comment]
This issue should be fixed in the upcoming 2.29
