### ISSUE TITLE
Same alert is coming thrice in slack channel 

### ISSUE THREAD

**Issue by jobinmat** [falcosecurity/falcosidekick#834]
**Describe the bug**

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Issif** [comment]
Can you provide more details please. Which alert is concerned?
Moreover, Falcosidekick is a proxy forwarder, it forwards to its outputs what it receives from Falco, if you receive multiple times the same alert, it means Falco has risen it several times.
