### ISSUE TITLE
I was not able to override Content-Type header  

### ISSUE THREAD

**Issue by PrettySolution** [falcosecurity/falcosidekick#856]
**Describe the bug**
I was not able to override Content-Type header as suggested in documentation for custom headers. 

Technically, I should be able to override the Content-Type header by adding the key and a value in the webhook.customheaders map as the content type is also just a header but set before the custom ones.

**How to reproduce it**

install falco chart 4.2.4, enable falcosidekick and set up webhook connector
check logs in falco-falcosidekick Pod: Webhook - Unexpected Response (415)

set falcosidekick.enabled = true
set falcosidekick.config.webhook.address = http://xxx.yyy.194.126:10029/falco
set falcosidekick.config.webhook.method = POST
set falcosidekick.config.webhook.checkcert = false
set falcosidekick.config.webhook.customHeaders = content-type:application/json

**Expected behaviour**

content-type header strictly set. 

- Falco version:

4.2.4
- Installation method:

Helm

**Comment by Issif** [comment]
The PR #857 fixes that issue.
