### ISSUE TITLE
Follow Prometheus naming convention for falco_events metric

### ISSUE THREAD

**Issue by cezkuj** [falcosecurity/falcosidekick#940]
**Motivation**
`falco_events` metric doesn't follow [Prometheus naming convention](https://prometheus.io/docs/practices/naming/#metric-names) causing issues with inferring its type in a monitoring system. In our case this is [NewRelic Prometheus integration that uses remote write protocol](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/#mapping). Metric is by default considered a gauge and needs manual overwrites to change its type to a counter.

**Feature**

Changing metric name from `falco_events` to `falco_events_total` 

**Additional context**

I am aware that changing metric name is a breaking change, but it would be nice to have it changed at some point :)

**Comment by Issif** [comment]
😥 I released the 2.29.0 yesterday.
Falco now exposes a Prometheus endpoint, so I wanted to remove some metrics in sidekick cause they are in double with those in Falco in 2.30. Could be the occasion to do both. I don't have any ETA
