### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by pyaillet** [falcosecurity/falcosidekick#96]
Hi !

Thank you all for bringing falco to the community.

I opened a PR on the project and saw that the PR template reference a CONTRIBUTING.md that doesn't exit on the repository.
Could it be copied from this : https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md ?

**Comment by Issif** [comment]
That's a fair point, we need to discuss about, the main `CONTRIBUTING.md` has some parts (C++ guidelines) which are really focused on `falco`
